# Basic
title: Poetry and Freak
subtitle: A pig is flying.
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Be patient. Time is Love.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Collections
 collections:
   projects:
     output: true
     permalink: /:collection/:path/

defaults:
# _projects
   - scope:
       path: ""
       type: projects
     values:
       layout: single
       author_profile: true
       read_time: true
       comments: # true
       share: true
       related: true

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
    - {title: CV}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
##comment:
  ##  disqus: vno-jekyll
    ## duoshuo: 
    
# Social
social:
    ##weibo: onevcat
    github: dramapig
    ##twitter: onevcat
    ##gplus: 107108267983477358170
    ##mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
